Repository datamol-io/graphium, pull requests merged in 2023-07, with the labels that each got.

#388 Clean dependencies and remove mordred deps
  env.yml
  graphium/features/properties.py
  graphium/trainer/predictor_summaries.py
  pyproject.toml
  requirements_ipu.txt
Labels: feature

#392 add google analytics support and little tweaks
  docs/_assets/css/custom-graphium.css
  docs/_assets/css/custom.css
  docs/_assets/js/google-analytics.js
  mkdocs.yml
Labels: feature

#393 Pin `pydantic` to `<2` cuz of `lightning`
  env.yml
Labels: fix

#403 Enable pytorch 2 in CI
  .github/workflows/test.yml
  env.yml
Labels: feature

#398 Made the TDC ADMET Benchmark group available in Graphium
  expts/configs/config_tdc_admet_demo.yaml
  graphium/data/__init__.py
  graphium/data/datamodule.py
  graphium/data/dataset.py
  graphium/utils/spaces.py
  notebooks/finetuning-on-tdc-admet-benchmark.ipynb
  tests/test_multitask_datamodule.py
Labels: feature

#402 Additional IPU test coverage
  .github/workflows/test.yml
  .github/workflows/test_ipu.yml
  graphium/ipu/ipu_utils.py
  tests/config_test_ipu_dataloader_multitask.yaml
  tests/test_ipu_dataloader.py
  tests/test_ipu_losses.py
  tests/test_ipu_options.py
  tests/test_ipu_to_dense_batch.py
Labels: enhancement, fix
