Repository datamol-io/graphium, pull requests merged in 2023-09, with the labels that each got.

#449 Various updates to graphium
  .gitignore
  README.md
  expts/hydra-configs/README.md
  expts/hydra-configs/architecture/largemix.yaml
  expts/hydra-configs/experiment/toymix_mpnn.yaml
  expts/hydra-configs/model/gine.yaml
  expts/hydra-configs/tasks/l1000_mcf7.yaml
  expts/hydra-configs/tasks/l1000_vcap.yaml
  expts/hydra-configs/tasks/largemix.yaml
  expts/hydra-configs/tasks/loss_metrics_datamodule/l1000_mcf7.yaml
  expts/hydra-configs/tasks/loss_metrics_datamodule/l1000_vcap.yaml
  expts/hydra-configs/tasks/loss_metrics_datamodule/largemix.yaml
  expts/hydra-configs/tasks/loss_metrics_datamodule/pcba_1328.yaml
  expts/hydra-configs/tasks/loss_metrics_datamodule/pcqm4m_g25.yaml
  expts/hydra-configs/tasks/loss_metrics_datamodule/pcqm4m_n4.yaml
  expts/hydra-configs/tasks/pcba_1328.yaml
  expts/hydra-configs/tasks/pcqm4m_g25.yaml
  expts/hydra-configs/tasks/pcqm4m_n4.yaml
  expts/hydra-configs/tasks/task_heads/l1000_mcf7.yaml
  expts/hydra-configs/tasks/task_heads/l1000_vcap.yaml
  expts/hydra-configs/tasks/task_heads/largemix.yaml
  expts/hydra-configs/tasks/task_heads/pcba_1328.yaml
  expts/hydra-configs/tasks/task_heads/pcqm4m_g25.yaml
  expts/hydra-configs/tasks/task_heads/pcqm4m_n4.yaml
  expts/hydra-configs/training/accelerator/largemix_cpu.yaml
  expts/hydra-configs/training/accelerator/largemix_gpu.yaml
  expts/hydra-configs/training/accelerator/largemix_ipu.yaml
  expts/hydra-configs/training/largemix.yaml
  expts/hydra-configs/training/model/largemix_gcn.yaml
  expts/hydra-configs/training/model/largemix_gin.yaml
  expts/hydra-configs/training/model/largemix_gine.yaml
  expts/hydra-configs/training/model/pcqm4m_gpspp.yaml
  expts/hydra-configs/training/model/pcqm4m_mpnn.yaml
  expts/hydra-configs/training/model/toymix_gcn.yaml
  expts/hydra-configs/training/model/toymix_gin.yaml
  expts/hydra-configs/training/pcqm4m.yaml
  graphium/data/datamodule.py
  graphium/data/dataset.py
  graphium/trainer/predictor.py
  tests/test_datamodule.py
Labels: fix, feature request

#454 Fixed the CLI command definition and data module preparation
  graphium/trainer/predictor.py
  pyproject.toml
Labels: bug, fix

#468 Minor fixes
  expts/hydra-configs/tasks/loss_metrics_datamodule/admet.yaml
  graphium/cli/train_finetune_test.py
  graphium/nn/architectures/encoder_manager.py
  graphium/nn/architectures/global_architectures.py
  graphium/nn/encoders/laplace_pos_encoder.py
  graphium/nn/pyg_layers/gps_pyg.py
  graphium/nn/pyg_layers/mpnn_pyg.py
  graphium/utils/spaces.py
Labels: fix

#471 Few mup updates
  .gitignore
  graphium/cli/train_finetune_test.py
  graphium/config/_loader.py
  graphium/nn/utils.py
  graphium/trainer/predictor.py
  graphium/trainer/predictor_options.py
  scripts/scale_mpnn.sh
Labels: bug
