Repository datamol-io/graphium, pull requests merged in 2023-08, with the labels that each got.

#421 Configs v2
  expts/hydra-configs/README.md
  expts/hydra-configs/architecture/toymix.yaml
  expts/hydra-configs/dataset/toymix.yaml
  expts/hydra-configs/main.yaml
  expts/hydra-configs/tasks/toymix.yaml
  expts/hydra-configs/training/accelerator/toymix_cpu.yaml
  expts/hydra-configs/training/accelerator/toymix_gpu.yaml
  expts/hydra-configs/training/accelerator/toymix_ipu.yaml
  expts/hydra-configs/training/model/toymix_gcn.yaml
  expts/hydra-configs/training/model/toymix_gin.yaml
  expts/hydra-configs/training/toymix.yaml
Labels: feature

#426 Fixed GatedGCN in float16. Minor cleanups.
  graphium/nn/architectures/global_architectures.py
  graphium/nn/pyg_layers/gated_gcn_pyg.py
Labels: fix

#429 Gpu mixed-precision overflow fix
  graphium/trainer/predictor.py
  graphium/trainer/predictor_summaries.py
  graphium/utils/tensor.py
  tests/test_utils.py
Labels: fix

#436 Strategy defaults to 'auto'
  graphium/config/_loader.py
Labels: fix

#442 Fix isinstance check and broadened tests to include more Python versions
  .github/workflows/test.yml
  graphium/finetuning/finetuning_architecture.py
Labels: fix

#444 Baselines for LargeMix
  .gitignore
  README.md
  docs/baseline.md
  docs/cli_references.md
  env.yml
  expts/hydra-configs/architecture/toymix.yaml
  expts/hydra-configs/finetuning/admet.yaml
  expts/hydra-configs/hparam_search/optuna.yaml
  expts/hydra-configs/training/model/toymix_gcn.yaml
  expts/hydra-configs/training/model/toymix_gin.yaml
  expts/main_run_multitask.py
  graphium/cli/__init__.py
  graphium/cli/__main__.py
  graphium/cli/data.py
  graphium/cli/finetune_utils.py
  graphium/cli/fingerprints.py
  graphium/cli/main.py
  graphium/cli/prepare_data.py
  graphium/cli/train_finetune.py
  graphium/config/_loader.py
  graphium/config/dummy_finetuning_from_task_head.yaml
  graphium/data/dataset.py
  graphium/finetuning/__init__.py
  graphium/finetuning/finetuning_architecture.py
  graphium/finetuning/utils.py
  graphium/hyper_param_search/__init__.py
  graphium/hyper_param_search/results.py
  graphium/trainer/predictor.py
  mkdocs.yml
  notebooks/compare-pretraining-finetuning-performance.ipynb
  pyproject.toml
  requirements_ipu.txt
  tests/test_finetuning.py
Labels: documentation

#447 Fix `strategy` argument for trainer
  graphium/config/_loader.py
Labels: bug

#448 Add dataloader_idx argument to callbacks
  graphium/ipu/ipu_wrapper.py
  graphium/trainer/predictor.py
Labels: bug

#441 WIP: Various improvements to the CLI endpoints
  .github/workflows/doc.yml
  README.md
  docs/api/graphium.finetuning.md
  docs/cli/graphium-train.md
  docs/cli/graphium.md
  docs/cli/reference.md
  graphium/cli/__main__.py
  graphium/cli/finetune_utils.py
  graphium/cli/train_finetune_test.py
  graphium/config/_loader.py
  graphium/finetuning/finetuning_architecture.py
  graphium/finetuning/fingerprinting.py
  graphium/finetuning/utils.py
  graphium/nn/architectures/global_architectures.py
  graphium/trainer/predictor.py
  mkdocs.yml
  tests/test_finetuning.py
  tests/test_ipu_training.py
Labels: feature request
